services:
  app:
    build: .
    restart: unless-stopped
    expose:
    - "80"
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      FB_ADDRESS: 0.0.0.0
      FB_PORT: "80"
    volumes:
    - file-data:/srv
    - file-database:/database
    - file-config:/config
    deploy:
      resources:
        limits:
          memory: '268435456'
          cpus: 0.5
        reservations: {}
    mem_limit: 268435456
    memswap_limit: 268435456
    cpus: 0.5
volumes:
  file-data: 
  file-database: 
  file-config:
